### PR TITLE
loki-wallet-cli: added locked_sweep_all command

### PR DESCRIPTION
**Pull request by jcktm**
Please review

### CODE REVIEW

**Comment by Haafingar** [comment]
Please include new changes (See Monero PR)

**Comment by jcktm** [comment]
They're in there, this is ready to go

**Comment by Haafingar** [comment]
Since the ring size is fixed in Loki, could you please amend this command to remove that as an option? The ring size will always be 10

**Comment by jcktm** [comment]
This was merged into dev branch before I could fix this, so I'll fix the ring size options for all the simplewallet commands in one go in another commit

**Pull request closed without merging**
