### PR TITLE
Interactive registration: part 1

### PR DESCRIPTION
**Pull request by sachaaaaa**
This PR will only add the interactive prompt and saving to disk of the registration parameters.
I will remove `get_service_node_registration_cmd` separately.
This is an early PR with the intention to get feedback.

A couple of open questions:
- Money is displayed with 9 digits of precision, overkill?
- I could use feedback on the actual phrasing of the prompts
- I am not sure if I am getting the correct block height
- I am not sure my logic is in the right file
- I assume we want to minimise overshooting the staking requirement, so at each participant iteration I display how much is left before the staking requirement is fulfilled.
- suggestion: I think it would be more user-friendly to prompt percentage as 0-100 instead of 0-1

Example of interactions:
Single participant (operator):
```
> prepare_registration
Current staking requirement: 100.000000000
Do you want to reserve portions of the stake for other participants? (Y/Yes/N/No):N
Enter the reward percentage reserved for operating costs [0.0-1.0]:0.5
Enter the loki address for the operator:abc
Reserved staking contribution: 100.000000000
Registration parameters saved.
```
Multiple participants, operator stakes the minimum:
```
prepare_registration 
Current staking requirement: 100.000000000
Do you want to reserve portions of the stake for other participants? (Y/Yes/N/No):Yes
Number of additional participants [1-3]:2
Enter the reward percentage reserved for operating costs [0.0-1.0]:0.5
Enter the loki address for the operator:a
Enter the total stake amount for the operator [25.000000000-100.000000000]:25
the operator will need to contribute 25.000000000.
Enter the loki address for participant 1:b
Enter the total stake amount for participant 1 [0.000000000-75.000000000]:20
Enter the loki address for participant 2:c
Enter the total stake amount for participant 2 [0.000000000-55.000000000]:20
Reserved staking contribution: 65.000000000
The remaining 35.000000000 will need to be filled by an external staker.
Registration parameters saved.
```
4 Participants, operator reserves more than minimum, but not enough amount reserved:
```
Current staking requirement: 100.000000000
Do you want to reserve portions of the stake for other participants? (Y/Yes/N/No):Yes
Number of additional participants [1-3]:3
Enter the reward percentage reserved for operating costs [0.0-1.0]:0.5
Enter the loki address for the operator:a
Enter the total stake amount for the operator [25.000000000-100.000000000]:50
Enter the amount that the operator will contribute initially [25.000000000-50.000000000]:30
Enter the loki address for participant 1:b
Enter the total stake amount for participant 1 [0.000000000-50.000000000]:21
Enter the loki address for participant 2:c
Enter the total stake amount for participant 2 [0.000000000-29.000000000]:17.54
Enter the loki address for participant 3:d
Enter the total stake amount for participant 3 [0.000000000-11.460000000]:10   
Reserved staking contribution: 98.540000000
Invalid parameters: the total contribution 98.540000000 does not meet the staking requirement of 100.000000000
```

### CODE REVIEW

**Comment by KeeJef** [comment]
For the individual staking case why do we ask this question ?

> Enter the reward percentage reserved for operating costs [0.0-1.0]:0.5

we assume that an individual staker will get the whole reward right? so why ask

Also is there any commands for creating an open pool, where contributions aren't explicitly set?

**Comment by Haafingar** [comment]
Be advised that the staking rules do not allow participants 2 or 3 to contribute less than 25% of the staking requirement. 

> Enter the reward percentage reserved for operating costs [0.0-1.0]:0.5

This is ambiguous, could be interpreted as a fraction up to 100%, or as a percentage up to 1%. I would suggest making the user present it as a percentage (ie. 25 instead of 0.25).

I would also suggest explaining each step more thoroughly. For example, 

> Enter the reward percentage reserved for operating costs [0.0-1.0]:0.5

could be perhaps better explained by stating 

`What percentage of the total staking reward would you like to take as an operator fee`

Lastly, there are 4 user flows which haven't wholly been considered in this design.

1. Operator wishes to run a solo stake. First question should be "Solo stake?" and if yes, take the operator address and skip to end.
2. Operator wishes to reserve some of the stake and leave the rest open ended. Question "Do you wish to reserve any portions for other contributors? If yes, make reservations and then if the staking rules are unbroken (3 or less contribs, all above 25%) and the total contributions != staking req, prompt the operator to allow open contributions for the remaining stake.
3. Operator wishes to reserve portions for the entire stake. As above, but if total contributions = staking req, proceed.
4. Operator wishes to leave the remaining stake open. 

Here is the question flow:

Solo Stake?
 Y: Operator Address? / Skip to end
 N: Next Question
Operator Fee?
Reserve How much for Operator?
Reserve any other portions for contribs?
 Y: How Many? (1-3)
 N: Prompt operator to allow open staking, then skip to end
Specify Address and Contribution for each Contributor
Staking Requirement Met?
 Y: Skip to end
 Y: Prompt operator to allow open staking, then skip to end
End: Prompt user to review staking arrangement, hit Y then generate command

**Comment by jcktm** [comment]
> Be advised that the staking rules do not allow participants 2 or 3 to contribute less than 25% of the staking requirement.

Unless e.g. participant 1 and 2 contribute 45% each... Then participant 3 could contribute 10%

**Comment by sachaaaaa** [comment]
Updated the scope of this PR, there is no more save-to-file, but it's reusing the existing functions to print the wallet command.

Example prompts:

Operator solo:
```
prepare_registration 
Current staking requirement: 100.000000000 loki
Will the operator contribute to the stake in its entirety? (Y/Yes/N/No):
Y
How much of that contribution will the operator stake initially?
100
Enter the loki address for the operator:
T6TWN91CQnNYyHUwenTi4qG2mY9mkj4LwAbnUuKAQcLMWdXq93XuaAhcWT4gSv53fwUV7M9qYiaLoDYAvvsexXkA1hKm45qju
Summary:
Operating costs as % of reward: 100%
Operator initial contribution: 100.000000000 loki
Contributor              Address                  Contribution             Contribution(%)          
___________              _______                  ____________             _______________          
Operator                 T6TWN9                   100.000000000            100.00                   
Do you confirm the information above is correct? (Y/Yes/N/No):
Y
Run this command in the wallet that will fund this registration:

register_service_node 1.000000 T6TWN91CQnNYyHUwenTi4qG2mY9mkj4LwAbnUuKAQcLMWdXq93XuaAhcWT4gSv53fwUV7M9qYiaLoDYAvvsexXkA1hKm45qju 1.000000 100.000000000 1535435669 796c90e11e534f5e4f58168b0e7654c8e2f8e7e6d02060a5a540fbae9e67c713 cb869ba8ba2dbdabdfb433a4ab4f1cef60c5ddc7108a9313ada7b1e42fd0c0020e625f372c959e99a95e36d088aecb5fcac239987f63a2ce4a7d52d135cbf305

This registration expires at 2018-08-28 05:54:29 AM. This should be in about 2 weeks. If it isn't, check this computer's clock
Please submit your registration into the blockchain before this time or it will be invalid.
```
Operator + open pool
```
prepare_registration 
Current staking requirement: 100.000000000 loki
Will the operator contribute to the stake in its entirety? (Y/Yes/N/No):
N
What percentage of the total staking reward would the operator like to take as an operator fee [0-100]%:
25.64%
What contribution should be reserved for the operator?
30
How much of that contribution will the operator stake initially?
27.85
Do you want to reserve portions of the stake for other contributors? (Y/Yes/N/No):
N
Enter the loki address for the operator:
T6TWN91CQnNYyHUwenTi4qG2mY9mkj4LwAbnUuKAQcLMWdXq93XuaAhcWT4gSv53fwUV7M9qYiaLoDYAvvsexXkA1hKm45qju
Total staking contributions reserved: 30.000000000 loki
Your total reservations do not equal the staking requirement.
You will leave the remaining portion of 70.000000000 open to contributions from anyone, and the Service Node will not activate until the full staking requirement is filled.
Is this ok? (Y/Yes/N/No):
Y
Summary:
Operating costs as % of reward: 25.64%
Operator initial contribution: 27.850000000 loki
Contributor              Address                  Contribution             Contribution(%)          
___________              _______                  ____________             _______________          
Operator                 T6TWN9                   30.000000000             30.00                    
(open)                                            70.000000000             70.00                    
Do you confirm the information above is correct? (Y/Yes/N/No):
Y
Run this command in the wallet that will fund this registration:

register_service_node 0.256400 T6TWN91CQnNYyHUwenTi4qG2mY9mkj4LwAbnUuKAQcLMWdXq93XuaAhcWT4gSv53fwUV7M9qYiaLoDYAvvsexXkA1hKm45qju 0.300000 27.850000000 1535435816 796c90e11e534f5e4f58168b0e7654c8e2f8e7e6d02060a5a540fbae9e67c713 e921192a8ffba04a176c500b7c9d770aab90ad10a3db5f9c2ddd67fae834fa06ed8970e709a7345288c2a4ab251b64e8fbed8ab24655f58c2e9556f83af35203

This registration expires at 2018-08-28 05:56:56 AM. This should be in about 2 weeks. If it isn't, check this computer's clock
Please submit your registration into the blockchain before this time or it will be invalid.
```
Operator + 1 reserved contributor
```
prepare_registration 
Current staking requirement: 100.000000000 loki
Will the operator contribute to the stake in its entirety? (Y/Yes/N/No):
N
What percentage of the total staking reward would the operator like to take as an operator fee [0-100]%:
10.87%
What contribution should be reserved for the operator?
29.99
How much of that contribution will the operator stake initially?
28.99
Do you want to reserve portions of the stake for other contributors? (Y/Yes/N/No):
Y
Number of additional contributors [1-3]:
1
Enter the loki address for the operator:
T6TWN91CQnNYyHUwenTi4qG2mY9mkj4LwAbnUuKAQcLMWdXq93XuaAhcWT4gSv53fwUV7M9qYiaLoDYAvvsexXkA1hKm45qju
Enter the loki address for contributor 1:
T6TWN91CQnNYyHUwenTi4qG2mY9mkj4LwAbnUuKAQcLMWdXq93XuaAhcWT4gSv53fwUV7M9qYiaLoDYAvvsexXkA1hKm45qju
What contribution should be reserved for contributor 1?
28.5
Total staking contributions reserved: 58.490000000 loki
Your total reservations do not equal the staking requirement.
You will leave the remaining portion of 41.510000000 open to contributions from anyone, and the Service Node will not activate until the full staking requirement is filled.
Is this ok? (Y/Yes/N/No):
Y
Summary:
Operating costs as % of reward: 10.87%
Operator initial contribution: 28.990000000 loki
Contributor              Address                  Contribution             Contribution(%)          
___________              _______                  ____________             _______________          
Operator                 T6TWN9                   29.990000000             29.99                    
Contributor 1            T6TWN9                   28.500000000             28.50                    
(open)                                            41.510000000             41.51                    
Do you confirm the information above is correct? (Y/Yes/N/No):
Y
Run this command in the wallet that will fund this registration:

register_service_node 0.108700 T6TWN91CQnNYyHUwenTi4qG2mY9mkj4LwAbnUuKAQcLMWdXq93XuaAhcWT4gSv53fwUV7M9qYiaLoDYAvvsexXkA1hKm45qju 0.299900 T6TWN91CQnNYyHUwenTi4qG2mY9mkj4LwAbnUuKAQcLMWdXq93XuaAhcWT4gSv53fwUV7M9qYiaLoDYAvvsexXkA1hKm45qju 0.285000 28.990000000 1535435918 796c90e11e534f5e4f58168b0e7654c8e2f8e7e6d02060a5a540fbae9e67c713 8e3bd0a7ba168be194e069606814bfad71daf8d00a09401976764b2d189a3d01302402dd9727dd3ca4bd8adf0cfe0cbed67e7690bdbcc0adc7ef5bae2deb5005

This registration expires at 2018-08-28 05:58:38 AM. This should be in about 2 weeks. If it isn't, check this computer's clock
Please submit your registration into the blockchain before this time or it will be invalid.
```
Operator + 2 contributors, last contribution is <25%
```
prepare_registration 
Current staking requirement: 100.000000000 loki
Will the operator contribute to the stake in its entirety? (Y/Yes/N/No):
N
What percentage of the total staking reward would the operator like to take as an operator fee [0-100]%:
5.5%
What contribution should be reserved for the operator?
45.0
How much of that contribution will the operator stake initially?
25
Do you want to reserve portions of the stake for other contributors? (Y/Yes/N/No):
Y
Number of additional contributors [1-3]:
2
Enter the loki address for the operator:
T6TWN91CQnNYyHUwenTi4qG2mY9mkj4LwAbnUuKAQcLMWdXq93XuaAhcWT4gSv53fwUV7M9qYiaLoDYAvvsexXkA1hKm45qju
Enter the loki address for contributor 1:
T6TWN91CQnNYyHUwenTi4qG2mY9mkj4LwAbnUuKAQcLMWdXq93XuaAhcWT4gSv53fwUV7M9qYiaLoDYAvvsexXkA1hKm45qju
What contribution should be reserved for contributor 1?
45
Enter the loki address for contributor 2:
T6TWN91CQnNYyHUwenTi4qG2mY9mkj4LwAbnUuKAQcLMWdXq93XuaAhcWT4gSv53fwUV7M9qYiaLoDYAvvsexXkA1hKm45qju
What contribution should be reserved for contributor 2?
10
Total staking contributions reserved: 100.000000000 loki
Summary:
Operating costs as % of reward: 5.5%
Operator initial contribution: 25.000000000 loki
Contributor              Address                  Contribution             Contribution(%)          
___________              _______                  ____________             _______________          
Operator                 T6TWN9                   45.000000000             45.00                    
Contributor 1            T6TWN9                   45.000000000             45.00                    
Contributor 2            T6TWN9                   10.000000000             10.00                    
Do you confirm the information above is correct? (Y/Yes/N/No):
Y
2018-08-14 06:00:04.035	  0x70001114c000	ERROR	service_nodes	src/cryptonote_core/service_node_list.cpp:884	Invalid portion amount: 0.100000. Must be at least 0.25 and no more than 1
2018-08-14 06:00:04.044	  0x70001114c000	ERROR	service_nodes	src/cryptonote_core/service_node_list.cpp:924	Could not convert registration args
Error: Unsuccessful -- Failed to make registration command
```
( This should be fixed in https://github.com/loki-project/loki/pull/140)

**Comment by jcktm** [comment]
moved to https://github.com/loki-project/loki/pull/147

**Pull request closed without merging**
